# These are supported funding model platforms

## Supported
github: K3V1991 

## Currently unsupported
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
custom:
